//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITS.MapObjects.RoadRepairingMapObject.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITS.MapObjects.RoadRepairingMapObject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение изменений.
        /// </summary>
        internal static string AcceptGroupName {
            get {
                return ResourceManager.GetString("AcceptGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AcceptImageSource {
            get {
                object obj = ResourceManager.GetObject("AcceptImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить изменения.
        /// </summary>
        internal static string AcceptUserFunctionalName {
            get {
                return ResourceManager.GetString("AcceptUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddRoadRepairImageSource {
            get {
                object obj = ResourceManager.GetObject("AddRoadRepairImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать дорожные работы.
        /// </summary>
        internal static string AddRoadRepairUserFunctionalName {
            get {
                return ResourceManager.GetString("AddRoadRepairUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение изменений.
        /// </summary>
        internal static string CancelGroupName {
            get {
                return ResourceManager.GetString("CancelGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CancelImageSource {
            get {
                object obj = ResourceManager.GetObject("CancelImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить изменения.
        /// </summary>
        internal static string CancelUserFunctionalName {
            get {
                return ResourceManager.GetString("CancelUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteRoadRepairImageSource {
            get {
                object obj = ResourceManager.GetObject("DeleteRoadRepairImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить дорожные работы.
        /// </summary>
        internal static string DeleteRoadRepairUserFunctionalName {
            get {
                return ResourceManager.GetString("DeleteRoadRepairUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструменты.
        /// </summary>
        internal static string DirGroupName {
            get {
                return ResourceManager.GetString("DirGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditGeometryRoadRepairImageSource {
            get {
                object obj = ResourceManager.GetObject("EditGeometryRoadRepairImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать геометрию дорожных работ.
        /// </summary>
        internal static string EditGeometryRoadRepairUserFunctionalName {
            get {
                return ResourceManager.GetString("EditGeometryRoadRepairUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditRoadRepairImageSource {
            get {
                object obj = ResourceManager.GetObject("EditRoadRepairImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать дорожные работы.
        /// </summary>
        internal static string EditRoadRepairUserFunctionalName {
            get {
                return ResourceManager.GetString("EditRoadRepairUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведомости.
        /// </summary>
        internal static string FindRoadRepairGroupName {
            get {
                return ResourceManager.GetString("FindRoadRepairGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindRoadRepairImageSource {
            get {
                object obj = ResourceManager.GetObject("FindRoadRepairImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindRoadRepairImageSource1 {
            get {
                object obj = ResourceManager.GetObject("FindRoadRepairImageSource1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сводная ведомость дорожных работ.
        /// </summary>
        internal static string FindRoadRepairUserFunctionalName {
            get {
                return ResourceManager.GetString("FindRoadRepairUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведомости.
        /// </summary>
        internal static string InfoRoadRepairGroupName {
            get {
                return ResourceManager.GetString("InfoRoadRepairGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InfoRoadRepairImageSource {
            get {
                object obj = ResourceManager.GetObject("InfoRoadRepairImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о дорожных работах.
        /// </summary>
        internal static string InfoRoadRepairUserFunctionalName {
            get {
                return ResourceManager.GetString("InfoRoadRepairUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap itsgisWND_BG_11 {
            get {
                object obj = ResourceManager.GetObject("itsgisWND_BG_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap itsgisWND_BottomButton {
            get {
                object obj = ResourceManager.GetObject("itsgisWND_BottomButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дорожные работы.
        /// </summary>
        internal static string PluginToolName {
            get {
                return ResourceManager.GetString("PluginToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История изменений.
        /// </summary>
        internal static string RedoGroupName {
            get {
                return ResourceManager.GetString("RedoGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дорожные работы.
        /// </summary>
        internal static string RoadRepairAlias {
            get {
                return ResourceManager.GetString("RoadRepairAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string SelectRoadRepairInProgressGroupName {
            get {
                return ResourceManager.GetString("SelectRoadRepairInProgressGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполняются.
        /// </summary>
        internal static string SelectRoadRepairInProgressShortUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectRoadRepairInProgressShortUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectRoadRepairInProgressSmallImageSource {
            get {
                object obj = ResourceManager.GetObject("SelectRoadRepairInProgressSmallImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить выполняющиеся дорожные работы.
        /// </summary>
        internal static string SelectRoadRepairInProgressUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectRoadRepairInProgressUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string SelectRoadRepairMadeGroupName {
            get {
                return ResourceManager.GetString("SelectRoadRepairMadeGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнены.
        /// </summary>
        internal static string SelectRoadRepairMadeShortUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectRoadRepairMadeShortUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectRoadRepairMadeSmallImageSource {
            get {
                object obj = ResourceManager.GetObject("SelectRoadRepairMadeSmallImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить выполненные дорожные работы.
        /// </summary>
        internal static string SelectRoadRepairMadeUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectRoadRepairMadeUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string SelectRoadRepairWillBeMadeGroupName {
            get {
                return ResourceManager.GetString("SelectRoadRepairWillBeMadeGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запланированы.
        /// </summary>
        internal static string SelectRoadRepairWillBeMadeShortUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectRoadRepairWillBeMadeShortUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectRoadRepairWillBeMadeSmallImageSource {
            get {
                object obj = ResourceManager.GetObject("SelectRoadRepairWillBeMadeSmallImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить запланированные дорожные работы.
        /// </summary>
        internal static string SelectRoadRepairWillBeMadeUserFunctionalName {
            get {
                return ResourceManager.GetString("SelectRoadRepairWillBeMadeUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История изменений.
        /// </summary>
        internal static string UndoGroupName {
            get {
                return ResourceManager.GetString("UndoGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведомости.
        /// </summary>
        internal static string WorkSortCatalogGroupName {
            get {
                return ResourceManager.GetString("WorkSortCatalogGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WorkSortCatalogImageSource {
            get {
                object obj = ResourceManager.GetObject("WorkSortCatalogImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник работ.
        /// </summary>
        internal static string WorkSortCatalogUserFunctionalName {
            get {
                return ResourceManager.GetString("WorkSortCatalogUserFunctionalName", resourceCulture);
            }
        }
    }
}
